### ISSUE TITLE
Test Issue[For House Paying using Predictive Analytics model]

### ISSUE THREAD

**Issue by Shrey-Srivastava21** [Shrey-Srivastava21/House_Price_Prediction_Project#4]
/*I Create this issue for making this Model using Predictive Analytic*/

House Price Prediction Based on Various Parameters

The repository is a learning exercise to:

1.Apply the fundamental concepts of machine learning from an available dataset
2.Evaluate and interpret my results and justify my interpretation based on observed data set
3.Create notebooks that serve as computational records and document my thought process.
4.Identifying the problem and Data Sources
5.Exploratory Data Analysis
6.Pre-Processing the Data
7.Build model to predict the price of the House

**Comment by Tanay-Dwivedi** [comment]
This repo is useful for learning predictive analytics through the house prediction model.
